compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

packageExtensions:
  "@mantine/styles@*":
    dependencies:
      "@emotion/cache": "*"
      "@emotion/react": "*"
      "@emotion/serialize": "*"
      "@emotion/utils": "*"
  debug@*:
    dependencies:
      supports-color: "*"
  follow-redirects@*:
    dependencies:
      debug: "*"
  vite@*:
    dependencies:
      supports-color: "*"

pnpFallbackMode: all

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.1.1.cjs
