apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: healthsync-ingress
  namespace: health-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - health.aiacta.com
      secretName: healthsync-tls-cert
  rules:
    - host: health.aiacta.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: healthsync-service
                port:
                  number: 80
