apiVersion: v1
kind: Service
metadata:
  name: healthsync-service
  namespace: health-app
  labels:
    app: healthsync
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: healthsync
